INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, AGE) VALUES (1, 'John', 'Doe', 45);
INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, AGE) VALUES (2, 'Jane', 'Dawson', 35);

INSERT INTO PRODUCTS (ID, NAME, PRICE, CATEGORY, GENDER, COLOR, SIZE, REMAINING_COUNT) VALUES (
1, 'Nike Air', 150, 'FOOTWEAR', 'MALE', 'BLACK', 'L', 10);
INSERT INTO PRODUCTS (ID, NAME, PRICE, CATEGORY, GENDER, COLOR, SIZE, REMAINING_COUNT) VALUES (
2, 'Levis 501', 200, 'CLOTHES', 'FEMALE', 'BLUE', 'S', 5);