CREATE TABLE USERS (
  ID NUMBER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  FIRST_NAME VARCHAR(32) NOT NULL,
  LAST_NAME VARCHAR(32) NOT NULL,
  AGE NUMBER
);

CREATE TABLE PRODUCTS (
  ID NUMBER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(64) NOT NULL,
  PRICE NUMBER NOT NULL,
  CATEGORY VARCHAR(16) NOT NULL,
  GENDER VARCHAR(8) NOT NULL,
  COLOR VARCHAR(16) NOT NULL,
  SIZE VARCHAR(8) NOT NULL,
  REMAINING_COUNT NUMBER NOT NULL
);

CREATE TABLE ORDERS (
  ID NUMBER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  USER_ID NUMBER NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE ORDER_ITEMS (
  ORDER_ID NUMBER NOT NULL,
  PRODUCT_ID NUMBER NOT NULL,
  COUNT NUMBER NOT NULL,
  FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
);