CREATE TABLE USERS (
  ID NUMBER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  FIRST_NAME VARCHAR(32) NOT NULL,
  LAST_NAME VARCHAR(32) NOT NULL,
  AGE NUMBER
);

CREATE TABLE PRODUCTS (
  ID NUMBER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(64) NOT NULL,
  PRICE NUMBER NOT NULL,
  CATEGORY VARCHAR(16) NOT NULL,
  GENDER VARCHAR(8) NOT NULL,
  COLOR VARCHAR(16) NOT NULL,
  SIZE VARCHAR(8) NOT NULL,
  REMAINING_COUNT NUMBER NOT NULL
);

CREATE TABLE ORDERS (
  ID NUMBER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  USER NUMBER NOT NULL,
  FOREIGN KEY (USER) REFERENCES USERS(ID)
)

CREATE TABLE ORDERS_PRODUCTS (
  ID NUMBER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ORDER NUMBER NOT NULL,
  PRODUCT NUMBER NOT NULL,
  COUNT NUMBER NOT NULL,
  FOREIGN KEY (ORDER) REFERENCES ORDERS(ID),
  FOREIGN KEY (PRODUCT) REFERENCES PRODUCTS(ID)
)